<div class="container-fluid">
    <form method="post" id="loginForm">
        <fieldset>
            <div class="form-group">
                <label>用户名:</label>
                <input type="text" class="form-control" placeholder="请输入用户名或者手机号/邮箱" name="admin_username" id="admin_username">
            </div>
            <div class="form-group">
                <label>密码:</label>
                <input type="password" class="form-control" placeholder="请输入密码" name="admin_password" id="admin_password">
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="remember" checked>记住密码
                    </label>
                </div>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">登录</button>
    </form>
</div>