<div class="container-fluid">
    <form method="post" id="postForm">
        <fieldset>
            <div class="form-group">
                <label>昵称:</label>
                <input type="text" class="form-control" placeholder="输入投稿昵称" name="post_nickname" id="post_nickname">
            </div>
            <div class="form-group">
                <label>内容:</label>
                <input type="text" class="form-control" placeholder="请输入投稿内容:" name="post_content" id="post_content">
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">投稿</button>
    </form>
</div>